### ISSUE TITLE
Update the theme name in index.theme

### ISSUE THREAD

**Issue by romildo** [Joshaby/Adapta-Nord#1]
In `index.theme` the theme is still referred as Adapta and Adapta-Nokto.

**Comment by Joshaby** [comment]
Oh, I haven't changed that! Thanks!

**Comment by romildo** [comment]
Only the `[Desktop Entry]` session has been changed.

The `[X-GNOME-Metatheme]` session of `index.theme` should be changed too.

**Comment by Joshaby** [comment]
I already modified this, I think, this file does not hinder the use of themes for me!
