### ISSUE TITLE
Directory name misspelled

### ISSUE THREAD

**Issue by romildo** [Joshaby/Adapta-Nord#2]
The directory holding the theme is misspelled. It misses a `t`.

https://github.com/Joshaby/Adapta-Nord/tree/master/Pkg/usr/share/themes/Adapta-FrosBlue4

**Comment by Joshaby** [comment]
??

**Comment by romildo** [comment]
It is:
_Adapta-FrosBlue4_

Maye it should be:
_Adapta-Fros**t**Blue4_

It is missing a **t** before **B**.

The other theme (Adapta-Fros**t**Blue4-Nokto) has the **t**, so I suppose it is a spelling error.

![Screenshot_2020-03-29_11-26-25](https://user-images.githubusercontent.com/1217934/77851567-3d9b6b80-71b0-11ea-933f-da22fb9adf0d.png)

**Comment by Joshaby** [comment]
Ah! Now I get it! I didn't see this error! Thanks for notifying!
